module.exports = [
    {
      id: "19",
        name: "rattata",
        type: "Dark | Normal",
        height: "0.3",
        weight: "3.8",
        url: "https://i.imgur.com/YLEjNgc.png",
        hp: 30,
        atk: 56,
        def: 35,
        spatk: 25,
        spdef: 35,
        speed: 72
    },
    {
      id: "20",
        name: "raticate",
        type: "Dark | Normal",
        height: "0.7",
        weight: "25.5",
        url: "https://i.imgur.com/pWCY2fF.png",
        hp: "75",
        atk: "71",
        def: "70",
        spatk: "40",
        spdef: "80",
        speed: "77"
    },
    {
      id: "26",
        name: "raichu",
        type: "Electric | Psychic",
        height: "0.7",
        weight: "21.0",
        url: "https://i.imgur.com/YmAsYGw.png",
        hp: "60",
        atk: "85",
        def: "50",
        spatk: "95",
        spdef: "85",
        speed: "110"
    },
    {
      id: "sandshrew",
        name: "27",
        type: "Ice | Steel",
        height: "0.7",
        weight: "40.0",
        url: "https://i.imgur.com/3r4WaSP.png",
        hp: "50",
        atk: "75",
        def: "90",
        spatk: "10",
        spdef: "35",
        speed: "40"
    },
    {
      id: "28",
        name: "sandslash",
        type: "Ice | Steel",
        height: "1.2",
        weight: "55.0",
        url: "https://i.imgur.com/srZLnOV.png",
        hp: "75",
        atk: "100",
        def: "120",
        spatk: "25",
        spdef: "65",
        speed: "65"
    },
    {
      id: "37",
        name: "vulpix",
        type: "Ice",
        height: "0.6",
        weight: "9.9",
        url: "https://i.imgur.com/gMsqHt2.png",
        hp: "38",
        atk: "41",
        def: "40",
        spatk: "50",
        spdef: "65",
        speed: "65"
    },
    {
      id: "38",
        name: "ninetales",
        type: "Ice | Fairy",
        height: "1.1",
        weight: "19.9",
        url: "https://i.imgur.com/HO0TK3K.png",
        hp: "73",
        atk: "67",
        def: "75",
        spatk: "81",
        spdef: "100",
        speed: "109"
    },
    {
      id: "50",
        name: "diglett",
        type: "Ground | Steel",
        height: "0.2",
        weight: "1.0",
        url: "",
        hp: "10",
        atk: "55",
        def: "30",
        spatk: "35",
        spdef: "45",
        speed: "90"
    },
    {
      id: "51",
        name: "dugtrio",
        type: "Ground | Steel",
        height: "0.7",
        weight: "66.6",
        url: "",
        hp: "35",
        atk: "100",
        def: "60",
        spatk: "50",
        spdef: "70",
        speed: "110"
    },
    {
      id: "52",
        name: "meowth",
        type: "Dark",
        height: "0.4",
        weight: "4.2",
        url: "",
        hp: "40",
        atk: "35",
        def: "35",
        spatk: "50",
        spdef: "40",
        speed: "90"
    },
    {
      id: "53",
        name: "persian",
        type: "Dark",
        height: "1.1",
        weight: "33.0",
        url: "",
        hp: "65",
        atk: "60",
        def: "60",
        spatk: "75",
        spdef: "65",
        speed: "115"
    },
    {
      id: "74",
        name: "geodude",
        type: "Rock | Electric",
        height: "0.4",
        weight: "20.3",
        url: "",
        hp: "40",
        atk: "80",
        def: "100",
        spatk: "30",
        spdef: "30",
        speed: "20"
    },
    {
      id: "75",
        name: "graveler",
        type: "Rock | Electric",
        height: "1.0",
        weight: "110.0",
        url: "",
        hp: "55",
        atk: "95",
        def: "115",
        spatk: "45",
        spdef: "45",
        speed: "35"
    },
    {
      id: "76",
        name: "golem",
        type: "Rock | Electric",
        height: "1.7",
        weight: "316.0",
        url: "",
        hp: "80",
        atk: "120",
        def: "130",
        spatk: "55",
        spdef: "65",
        speed: "45"
    },
    {
      id: "88",
        name: "grimer",
        type: "Poison | Dark",
        height: "0.7",
        weight: "42.0",
        url: "",
        hp: "80",
        atk: "80",
        def: "50",
        spatk: "40",
        spdef: "50",
        speed: "25"
    },
	{
      id: "89",
        name: "muk",
        type: "Poison | Dark",
        height: "1.0",
        weight: "52.0",
        url: "",
        hp: "105",
        atk: "105",
        def: "75",
        spatk: "65",
        spdef: "100",
        speed: "50"
    },
	{
      id: "103",
        name: "exeggutor",
        type: "Grass | Dragon",
        height: "10.9",
        weight: "415.6",
        url: "",
        hp: "95",
        atk: "105",
        def: "85",
        spatk: "125",
        spdef: "75",
        speed: "45"
    },
	{
      id: "105",
        name: "marowak",
        type: "Fire | Ghost",
        height: "1.0",
        weight: "34.0",
        url: ":",
        hp: "60",
        atk: "80",
        def: "110",
        spatk: "50",
        spdef: "80",
        speed: "45"
    }
]